/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SigninRouteImport } from './routes/signin'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedSignupRouteImport } from './routes/_authenticated/signup'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile'
import { Route as AuthenticatedLogRouteImport } from './routes/_authenticated/log'
import { Route as AuthenticatedJoinRouteImport } from './routes/_authenticated/join'
import { Route as AuthenticatedInboxRouteImport } from './routes/_authenticated/inbox'
import { Route as AuthenticatedFeedRouteImport } from './routes/_authenticated/feed'
import { Route as AuthenticatedEditPreferencesRouteImport } from './routes/_authenticated/edit-preferences'
import { Route as AuthenticatedDiscoverRouteImport } from './routes/_authenticated/discover'
import { Route as AuthenticatedCheckoutReturnRouteImport } from './routes/_authenticated/checkout-return'
import { Route as AuthenticatedBillingRouteImport } from './routes/_authenticated/billing'
import { Route as AuthenticatedReportUserIdRouteImport } from './routes/_authenticated/report.$userId'
import { Route as AuthenticatedPeopleIdRouteImport } from './routes/_authenticated/people.$id'
import { Route as AuthenticatedGroupsIdRouteImport } from './routes/_authenticated/groups.$id'
import { Route as AuthenticatedConcertsNewRouteImport } from './routes/_authenticated/concerts.new'
import { Route as AuthenticatedConcertsIdRouteImport } from './routes/_authenticated/concerts.$id'
import { Route as AuthenticatedAdminReportsRouteImport } from './routes/_authenticated/admin.reports'
import { Route as AuthenticatedAdminFoundingRouteImport } from './routes/_authenticated/admin.founding'
import { Route as AuthenticatedAdminAttendanceRouteImport } from './routes/_authenticated/admin.attendance'
import { Route as ApiPublicPaymentsWebhookRouteImport } from './routes/api/public/payments/webhook'
import { Route as ApiPublicHooksInboxCronRouteImport } from './routes/api/public/hooks/inbox-cron'

const SigninRoute = SigninRouteImport.update({
  id: '/signin',
  path: '/signin',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSignupRoute = AuthenticatedSignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedLogRoute = AuthenticatedLogRouteImport.update({
  id: '/log',
  path: '/log',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedJoinRoute = AuthenticatedJoinRouteImport.update({
  id: '/join',
  path: '/join',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedInboxRoute = AuthenticatedInboxRouteImport.update({
  id: '/inbox',
  path: '/inbox',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedFeedRoute = AuthenticatedFeedRouteImport.update({
  id: '/feed',
  path: '/feed',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedEditPreferencesRoute =
  AuthenticatedEditPreferencesRouteImport.update({
    id: '/edit-preferences',
    path: '/edit-preferences',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDiscoverRoute = AuthenticatedDiscoverRouteImport.update({
  id: '/discover',
  path: '/discover',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCheckoutReturnRoute =
  AuthenticatedCheckoutReturnRouteImport.update({
    id: '/checkout-return',
    path: '/checkout-return',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedBillingRoute = AuthenticatedBillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedReportUserIdRoute =
  AuthenticatedReportUserIdRouteImport.update({
    id: '/report/$userId',
    path: '/report/$userId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPeopleIdRoute = AuthenticatedPeopleIdRouteImport.update({
  id: '/people/$id',
  path: '/people/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedGroupsIdRoute = AuthenticatedGroupsIdRouteImport.update({
  id: '/groups/$id',
  path: '/groups/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedConcertsNewRoute =
  AuthenticatedConcertsNewRouteImport.update({
    id: '/concerts/new',
    path: '/concerts/new',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedConcertsIdRoute = AuthenticatedConcertsIdRouteImport.update({
  id: '/concerts/$id',
  path: '/concerts/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminReportsRoute =
  AuthenticatedAdminReportsRouteImport.update({
    id: '/admin/reports',
    path: '/admin/reports',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminFoundingRoute =
  AuthenticatedAdminFoundingRouteImport.update({
    id: '/admin/founding',
    path: '/admin/founding',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminAttendanceRoute =
  AuthenticatedAdminAttendanceRouteImport.update({
    id: '/admin/attendance',
    path: '/admin/attendance',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const ApiPublicPaymentsWebhookRoute =
  ApiPublicPaymentsWebhookRouteImport.update({
    id: '/api/public/payments/webhook',
    path: '/api/public/payments/webhook',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksInboxCronRoute = ApiPublicHooksInboxCronRouteImport.update({
  id: '/api/public/hooks/inbox-cron',
  path: '/api/public/hooks/inbox-cron',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signin': typeof SigninRoute
  '/billing': typeof AuthenticatedBillingRoute
  '/checkout-return': typeof AuthenticatedCheckoutReturnRoute
  '/discover': typeof AuthenticatedDiscoverRoute
  '/edit-preferences': typeof AuthenticatedEditPreferencesRoute
  '/feed': typeof AuthenticatedFeedRoute
  '/inbox': typeof AuthenticatedInboxRoute
  '/join': typeof AuthenticatedJoinRoute
  '/log': typeof AuthenticatedLogRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/signup': typeof AuthenticatedSignupRoute
  '/admin/attendance': typeof AuthenticatedAdminAttendanceRoute
  '/admin/founding': typeof AuthenticatedAdminFoundingRoute
  '/admin/reports': typeof AuthenticatedAdminReportsRoute
  '/concerts/$id': typeof AuthenticatedConcertsIdRoute
  '/concerts/new': typeof AuthenticatedConcertsNewRoute
  '/groups/$id': typeof AuthenticatedGroupsIdRoute
  '/people/$id': typeof AuthenticatedPeopleIdRoute
  '/report/$userId': typeof AuthenticatedReportUserIdRoute
  '/api/public/hooks/inbox-cron': typeof ApiPublicHooksInboxCronRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signin': typeof SigninRoute
  '/billing': typeof AuthenticatedBillingRoute
  '/checkout-return': typeof AuthenticatedCheckoutReturnRoute
  '/discover': typeof AuthenticatedDiscoverRoute
  '/edit-preferences': typeof AuthenticatedEditPreferencesRoute
  '/feed': typeof AuthenticatedFeedRoute
  '/inbox': typeof AuthenticatedInboxRoute
  '/join': typeof AuthenticatedJoinRoute
  '/log': typeof AuthenticatedLogRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/signup': typeof AuthenticatedSignupRoute
  '/admin/attendance': typeof AuthenticatedAdminAttendanceRoute
  '/admin/founding': typeof AuthenticatedAdminFoundingRoute
  '/admin/reports': typeof AuthenticatedAdminReportsRoute
  '/concerts/$id': typeof AuthenticatedConcertsIdRoute
  '/concerts/new': typeof AuthenticatedConcertsNewRoute
  '/groups/$id': typeof AuthenticatedGroupsIdRoute
  '/people/$id': typeof AuthenticatedPeopleIdRoute
  '/report/$userId': typeof AuthenticatedReportUserIdRoute
  '/api/public/hooks/inbox-cron': typeof ApiPublicHooksInboxCronRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signin': typeof SigninRoute
  '/_authenticated/billing': typeof AuthenticatedBillingRoute
  '/_authenticated/checkout-return': typeof AuthenticatedCheckoutReturnRoute
  '/_authenticated/discover': typeof AuthenticatedDiscoverRoute
  '/_authenticated/edit-preferences': typeof AuthenticatedEditPreferencesRoute
  '/_authenticated/feed': typeof AuthenticatedFeedRoute
  '/_authenticated/inbox': typeof AuthenticatedInboxRoute
  '/_authenticated/join': typeof AuthenticatedJoinRoute
  '/_authenticated/log': typeof AuthenticatedLogRoute
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/_authenticated/signup': typeof AuthenticatedSignupRoute
  '/_authenticated/admin/attendance': typeof AuthenticatedAdminAttendanceRoute
  '/_authenticated/admin/founding': typeof AuthenticatedAdminFoundingRoute
  '/_authenticated/admin/reports': typeof AuthenticatedAdminReportsRoute
  '/_authenticated/concerts/$id': typeof AuthenticatedConcertsIdRoute
  '/_authenticated/concerts/new': typeof AuthenticatedConcertsNewRoute
  '/_authenticated/groups/$id': typeof AuthenticatedGroupsIdRoute
  '/_authenticated/people/$id': typeof AuthenticatedPeopleIdRoute
  '/_authenticated/report/$userId': typeof AuthenticatedReportUserIdRoute
  '/api/public/hooks/inbox-cron': typeof ApiPublicHooksInboxCronRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/forgot-password'
    | '/reset-password'
    | '/signin'
    | '/billing'
    | '/checkout-return'
    | '/discover'
    | '/edit-preferences'
    | '/feed'
    | '/inbox'
    | '/join'
    | '/log'
    | '/profile'
    | '/signup'
    | '/admin/attendance'
    | '/admin/founding'
    | '/admin/reports'
    | '/concerts/$id'
    | '/concerts/new'
    | '/groups/$id'
    | '/people/$id'
    | '/report/$userId'
    | '/api/public/hooks/inbox-cron'
    | '/api/public/payments/webhook'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/forgot-password'
    | '/reset-password'
    | '/signin'
    | '/billing'
    | '/checkout-return'
    | '/discover'
    | '/edit-preferences'
    | '/feed'
    | '/inbox'
    | '/join'
    | '/log'
    | '/profile'
    | '/signup'
    | '/admin/attendance'
    | '/admin/founding'
    | '/admin/reports'
    | '/concerts/$id'
    | '/concerts/new'
    | '/groups/$id'
    | '/people/$id'
    | '/report/$userId'
    | '/api/public/hooks/inbox-cron'
    | '/api/public/payments/webhook'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/forgot-password'
    | '/reset-password'
    | '/signin'
    | '/_authenticated/billing'
    | '/_authenticated/checkout-return'
    | '/_authenticated/discover'
    | '/_authenticated/edit-preferences'
    | '/_authenticated/feed'
    | '/_authenticated/inbox'
    | '/_authenticated/join'
    | '/_authenticated/log'
    | '/_authenticated/profile'
    | '/_authenticated/signup'
    | '/_authenticated/admin/attendance'
    | '/_authenticated/admin/founding'
    | '/_authenticated/admin/reports'
    | '/_authenticated/concerts/$id'
    | '/_authenticated/concerts/new'
    | '/_authenticated/groups/$id'
    | '/_authenticated/people/$id'
    | '/_authenticated/report/$userId'
    | '/api/public/hooks/inbox-cron'
    | '/api/public/payments/webhook'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SigninRoute: typeof SigninRoute
  ApiPublicHooksInboxCronRoute: typeof ApiPublicHooksInboxCronRoute
  ApiPublicPaymentsWebhookRoute: typeof ApiPublicPaymentsWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signin': {
      id: '/signin'
      path: '/signin'
      fullPath: '/signin'
      preLoaderRoute: typeof SigninRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/signup': {
      id: '/_authenticated/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof AuthenticatedSignupRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/log': {
      id: '/_authenticated/log'
      path: '/log'
      fullPath: '/log'
      preLoaderRoute: typeof AuthenticatedLogRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/join': {
      id: '/_authenticated/join'
      path: '/join'
      fullPath: '/join'
      preLoaderRoute: typeof AuthenticatedJoinRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/inbox': {
      id: '/_authenticated/inbox'
      path: '/inbox'
      fullPath: '/inbox'
      preLoaderRoute: typeof AuthenticatedInboxRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/feed': {
      id: '/_authenticated/feed'
      path: '/feed'
      fullPath: '/feed'
      preLoaderRoute: typeof AuthenticatedFeedRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/edit-preferences': {
      id: '/_authenticated/edit-preferences'
      path: '/edit-preferences'
      fullPath: '/edit-preferences'
      preLoaderRoute: typeof AuthenticatedEditPreferencesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/discover': {
      id: '/_authenticated/discover'
      path: '/discover'
      fullPath: '/discover'
      preLoaderRoute: typeof AuthenticatedDiscoverRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/checkout-return': {
      id: '/_authenticated/checkout-return'
      path: '/checkout-return'
      fullPath: '/checkout-return'
      preLoaderRoute: typeof AuthenticatedCheckoutReturnRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/billing': {
      id: '/_authenticated/billing'
      path: '/billing'
      fullPath: '/billing'
      preLoaderRoute: typeof AuthenticatedBillingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/report/$userId': {
      id: '/_authenticated/report/$userId'
      path: '/report/$userId'
      fullPath: '/report/$userId'
      preLoaderRoute: typeof AuthenticatedReportUserIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/people/$id': {
      id: '/_authenticated/people/$id'
      path: '/people/$id'
      fullPath: '/people/$id'
      preLoaderRoute: typeof AuthenticatedPeopleIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/groups/$id': {
      id: '/_authenticated/groups/$id'
      path: '/groups/$id'
      fullPath: '/groups/$id'
      preLoaderRoute: typeof AuthenticatedGroupsIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/concerts/new': {
      id: '/_authenticated/concerts/new'
      path: '/concerts/new'
      fullPath: '/concerts/new'
      preLoaderRoute: typeof AuthenticatedConcertsNewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/concerts/$id': {
      id: '/_authenticated/concerts/$id'
      path: '/concerts/$id'
      fullPath: '/concerts/$id'
      preLoaderRoute: typeof AuthenticatedConcertsIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/reports': {
      id: '/_authenticated/admin/reports'
      path: '/admin/reports'
      fullPath: '/admin/reports'
      preLoaderRoute: typeof AuthenticatedAdminReportsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/founding': {
      id: '/_authenticated/admin/founding'
      path: '/admin/founding'
      fullPath: '/admin/founding'
      preLoaderRoute: typeof AuthenticatedAdminFoundingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/attendance': {
      id: '/_authenticated/admin/attendance'
      path: '/admin/attendance'
      fullPath: '/admin/attendance'
      preLoaderRoute: typeof AuthenticatedAdminAttendanceRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/payments/webhook': {
      id: '/api/public/payments/webhook'
      path: '/api/public/payments/webhook'
      fullPath: '/api/public/payments/webhook'
      preLoaderRoute: typeof ApiPublicPaymentsWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/inbox-cron': {
      id: '/api/public/hooks/inbox-cron'
      path: '/api/public/hooks/inbox-cron'
      fullPath: '/api/public/hooks/inbox-cron'
      preLoaderRoute: typeof ApiPublicHooksInboxCronRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedBillingRoute: typeof AuthenticatedBillingRoute
  AuthenticatedCheckoutReturnRoute: typeof AuthenticatedCheckoutReturnRoute
  AuthenticatedDiscoverRoute: typeof AuthenticatedDiscoverRoute
  AuthenticatedEditPreferencesRoute: typeof AuthenticatedEditPreferencesRoute
  AuthenticatedFeedRoute: typeof AuthenticatedFeedRoute
  AuthenticatedInboxRoute: typeof AuthenticatedInboxRoute
  AuthenticatedJoinRoute: typeof AuthenticatedJoinRoute
  AuthenticatedLogRoute: typeof AuthenticatedLogRoute
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
  AuthenticatedSignupRoute: typeof AuthenticatedSignupRoute
  AuthenticatedAdminAttendanceRoute: typeof AuthenticatedAdminAttendanceRoute
  AuthenticatedAdminFoundingRoute: typeof AuthenticatedAdminFoundingRoute
  AuthenticatedAdminReportsRoute: typeof AuthenticatedAdminReportsRoute
  AuthenticatedConcertsIdRoute: typeof AuthenticatedConcertsIdRoute
  AuthenticatedConcertsNewRoute: typeof AuthenticatedConcertsNewRoute
  AuthenticatedGroupsIdRoute: typeof AuthenticatedGroupsIdRoute
  AuthenticatedPeopleIdRoute: typeof AuthenticatedPeopleIdRoute
  AuthenticatedReportUserIdRoute: typeof AuthenticatedReportUserIdRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedBillingRoute: AuthenticatedBillingRoute,
  AuthenticatedCheckoutReturnRoute: AuthenticatedCheckoutReturnRoute,
  AuthenticatedDiscoverRoute: AuthenticatedDiscoverRoute,
  AuthenticatedEditPreferencesRoute: AuthenticatedEditPreferencesRoute,
  AuthenticatedFeedRoute: AuthenticatedFeedRoute,
  AuthenticatedInboxRoute: AuthenticatedInboxRoute,
  AuthenticatedJoinRoute: AuthenticatedJoinRoute,
  AuthenticatedLogRoute: AuthenticatedLogRoute,
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
  AuthenticatedSignupRoute: AuthenticatedSignupRoute,
  AuthenticatedAdminAttendanceRoute: AuthenticatedAdminAttendanceRoute,
  AuthenticatedAdminFoundingRoute: AuthenticatedAdminFoundingRoute,
  AuthenticatedAdminReportsRoute: AuthenticatedAdminReportsRoute,
  AuthenticatedConcertsIdRoute: AuthenticatedConcertsIdRoute,
  AuthenticatedConcertsNewRoute: AuthenticatedConcertsNewRoute,
  AuthenticatedGroupsIdRoute: AuthenticatedGroupsIdRoute,
  AuthenticatedPeopleIdRoute: AuthenticatedPeopleIdRoute,
  AuthenticatedReportUserIdRoute: AuthenticatedReportUserIdRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SigninRoute: SigninRoute,
  ApiPublicHooksInboxCronRoute: ApiPublicHooksInboxCronRoute,
  ApiPublicPaymentsWebhookRoute: ApiPublicPaymentsWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
